import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { ScaffoldOptions } from './types.js';

/**
 * Generate Docker files for the project
 */
export async function generateDockerFiles(
	outputDir: string,
	options: Partial<ScaffoldOptions> = {},
): Promise<string[]> {
	const createdFiles: string[] = [];
	const isBun = options.runtime !== 'node';

	// Generate Dockerfile
	const dockerfilePath = join(outputDir, 'Dockerfile');
	await generateDockerfile(dockerfilePath, isBun, options.projectName);
	createdFiles.push(dockerfilePath);

	// Generate docker-compose.yml
	const composePath = join(outputDir, 'docker-compose.yml');
	await generateDockerCompose(composePath, options.projectName || 'app');
	createdFiles.push(composePath);

	// Generate .dockerignore
	const dockerignorePath = join(outputDir, '.dockerignore');
	await generateDockerignore(dockerignorePath, isBun);
	createdFiles.push(dockerignorePath);

	return createdFiles;
}

/**
 * Generate Dockerfile
 */
async function generateDockerfile(
	outputPath: string,
	isBun: boolean,
	_projectName?: string,
): Promise<void> {
	let content: string;

	if (isBun) {
		content = `# Dockerfile for Elysia/Bun API
# Generated by Foxen migration tool

# Use official Bun image
FROM oven/bun:1 AS base
WORKDIR /app

# Install dependencies
FROM base AS deps
COPY package.json bun.lockb* ./
RUN bun install --frozen-lockfile

# Build stage
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN bun run build

# Production stage
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

# Copy built files
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Create non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 elysia
USER elysia

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["bun", "run", "dist/index.js"]
`;
	} else {
		content = `# Dockerfile for Elysia/Node API
# Generated by Foxen migration tool

# Use official Node.js image
FROM node:22-alpine AS base
WORKDIR /app

# Install dependencies
FROM base AS deps
COPY package.json package-lock.json* ./
RUN npm ci

# Build stage
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# Production stage
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

# Copy built files
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Create non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 elysia
USER elysia

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "dist/index.js"]
`;
	}

	await writeFile(outputPath, content);
}

/**
 * Generate docker-compose.yml
 */
async function generateDockerCompose(outputPath: string, serviceName: string): Promise<void> {
	const content = `# Docker Compose for Elysia API
# Generated by Foxen migration tool

services:
  ${serviceName}:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    # Uncomment to add database service
    # depends_on:
    #   - db
    restart: unless-stopped

  # Uncomment to add PostgreSQL database
  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_USER: \${POSTGRES_USER:-postgres}
  #     POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-postgres}
  #     POSTGRES_DB: \${POSTGRES_DB:-app}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # Uncomment to add Redis cache
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

# volumes:
#   postgres_data:
#   redis_data:
`;

	await writeFile(outputPath, content);
}

/**
 * Generate .dockerignore
 */
async function generateDockerignore(outputPath: string, isBun: boolean): Promise<void> {
	const lines = [
		'# Dependencies',
		'node_modules/',
		'',
		'# Build artifacts',
		'dist/',
		'.next/',
		'out/',
		'',
		'# Version control',
		'.git/',
		'.gitignore',
		'',
		'# IDE',
		'.idea/',
		'.vscode/',
		'*.swp',
		'*.swo',
		'',
		'# Environment files',
		'.env',
		'.env.local',
		'.env.*.local',
		'',
		'# Logs',
		'*.log',
		'npm-debug.log*',
		'',
		'# Test files',
		'tests/',
		'*.test.ts',
		'*.spec.ts',
		'coverage/',
		'',
		'# Documentation',
		'README.md',
		'docs/',
		'',
		'# Docker',
		'Dockerfile',
		'docker-compose.yml',
		'.dockerignore',
	];

	if (isBun) {
		lines.push('', '# Bun', 'bun.lockb');
	} else {
		lines.push('', '# Package manager', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml');
	}

	await writeFile(outputPath, `${lines.join('\n')}\n`);
}
